### PR TITLE
Add basic optional topology generation tests

### PR DESCRIPTION
**Pull request by e-mcginnis**
Shuffle topo generation test currently fails with:

```
DEBUG: /home/solidhal/katana/katana-enterprise/external/katana/libgalois/test/property-graph-optional-topologies.cpp:47: ##### Testing ShuffleTopology Generation #####
DEBUG: /home/solidhal/katana/katana-enterprise/external/katana/libtsuba/src/RDG.cpp:545: ReadPartMetadata master sz: 1 mirrors sz: 1 h2nod sz: 1 h20e sz: 1 l2u sz: 29946 l2g sz: 0
WARNING: /home/solidhal/katana/katana-enterprise/external/katana/libgalois/src/PropertyGraph.cpp:398: Loading types from properties.
WARNING: /home/solidhal/katana/katana-enterprise/external/katana/libsupport/include/katana/EntityTypeManager.h:104: assigning entity type ids from properties with 31 properties loaded
WARNING: /home/solidhal/katana/katana-enterprise/external/katana/libsupport/include/katana/EntityTypeManager.h:107: store the RDG to avoid overhead from assigning entity type ids from properties in the future
WARNING: /home/solidhal/katana/katana-enterprise/external/katana/libsupport/include/katana/EntityTypeManager.h:104: assigning entity type ids from properties with 18 properties loaded
WARNING: /home/solidhal/katana/katana-enterprise/external/katana/libsupport/include/katana/EntityTypeManager.h:107: store the RDG to avoid overhead from assigning entity type ids from properties in the future
ERROR: /home/solidhal/katana/katana-enterprise/external/katana/libgalois/include/katana/GraphTopology.h:412: assertion not true: std::is_sorted(degrees.begin(), degrees.end())
```

reverting commit `8159e5a98ed55908c94cbcfb23c7f2051b3c8530` makes this test pass again

### CODE REVIEW

**Comment by e-mcginnis** [comment]
this change is to blame for the failure https://github.com/KatanaGraph/katana/blob/8159e5a98ed55908c94cbcfb23c7f2051b3c8530/libgalois/src/GraphTopology.cpp#L307

flipping it back to 
```
return d1 < d2
```
makes the test pass

**Comment by e-mcginnis** [comment]
From speaking with @amberhassaan the assert is actually what is broken now, flipped the assert to check for the new ordering

**Review by tylershunt — COMMENTED** [review]
Looks good to me, I don't have enough context to unilaterally approve though. Will defer to @amberhassaan

**Comment by amberhassaan** [comment]
> From speaking with @amberhassaan the assert is actually what is broken now, flipped the assert to check for the new ordering

Yes, thank you. Initially ShuffleTopology used to sort degrees in ascending order which broke Triangle Counting's performance (so much that  12s run wouldn't finish for hours). The right thing was to sort in `descending` order for Triangle Counting.

**Pull request closed without merging**
