### PR TITLE
Rename check_format.sh to check_cpp_format.sh

### PR DESCRIPTION
**Pull request by ddn0**
I have no idea if the change from `check_format.sh` to `check_format_cpp.sh` was intentional:

https://github.com/KatanaGraph/katana/pull/108/files#diff-cbbd712c2ceee5e4eb3fa6ce53f0a64981c3868a3729d638c87ab413e77ff4bfL33

But if it was, this PR completes the change by renaming files so that `check_all.sh` works again.

### CODE REVIEW

**Comment by aneeshdurg** [comment]
What if we created a new workflow that runs check_all.sh?

**Review by aneeshdurg — APPROVED** [review]

**Review by arthurp — APPROVED** [review]
Thanks!

**Comment by ddn0** [comment]
> What if we created a new workflow that runs check_all.sh?

I don't have a strong preference either way.

I don't use `check_all.sh` myself.

There seem to be slight differences about what to check (golang or not, where to find text files) between this repo and the _other_ one. The other repo also rechecks things here, which I find useful, but may be surprising to some.

**Review by tylershunt — APPROVED** [review]

**Comment by ddn0** [comment]
@aneeshdurg you still want a `check_all.sh` workflow?

**Comment by aneeshdurg** [comment]
yeah, one of the ways it could be useful is if you have transient errors in your lint (e.g. due to a failure in apt update or something), you can ask it to re-run the workflow without re-running expensive tests. Plus it gives us a reason to maintain `check_all.sh` around (which is probably a good thing since it's a nice front door to our lint system as a whole).

I don't have super strong feelings about it though, and it's definitely not a blocker for this PR

**Comment by ddn0** [comment]
I'll put it in the idea hopper :D

**Pull request merged**
