### PR TITLE
bump input version to bring in storage_format_v2 graph

### PR DESCRIPTION
**Pull request by e-mcginnis**
to be merged once katana-inputs-v26.tar.gz is uploaded

### CODE REVIEW

**Review by scober — APPROVED** [review]
What changes are in the new inputs?

**Comment by e-mcginnis** [comment]
the new input is `./propertygraphs/ldbc_003_storage_format_version_2` which is the `ldbc_003` graph but bumped to the current storage version (2). This is required for the libtsuba test added in https://github.com/KatanaGraph/katana/pull/588, since going from storage_format_version=1 (aka, no storage_format_version) to storage_format_version=2 required libgalois to extract the EntityTypeIDs from properties, and a libtsuba test can't really rely on libgalois.

**Comment by e-mcginnis** [comment]
No other changes to the inputs, besides adding that new one, were made.

**Comment by e-mcginnis** [comment]
https://katana-ci-public.s3.us-east-1.amazonaws.com/inputs/katana-inputs-v26.tar.gz now available

**Pull request merged**
