### PR TITLE
Fix typos in 18 files [KAT-4410]

### PR DESCRIPTION
**Pull request by bobdc**
After spellchecking all of the HTML doc I tracked down the source of each and corrected it there. if you are a reviewer of this ticket you were shown as the last person to touch one of the listed `*.py*` or `cpp` files. Many edits are simply the changing of one character in a comment.

### CODE REVIEW

**Review by e-mcginnis — APPROVED** [review]
LGTM!

**Review by amazloumi — APPROVED** [review]
Thanks for this checking. looks fine on my end as well.

**Review by JamesFCoffey — APPROVED** [review]

**Review by arthurp — APPROVED** [review]
I apparently need to use my spell checker more.

**Review by dqawami — APPROVED** [review]
Appreciate you fixing comment typos!

**Pull request merged**
