### PR TITLE
Update conan used to 1.36.

### PR DESCRIPTION
**Pull request by arthurp**
This may fix issues related to conan thrift package that @gliga has been having.

### CODE REVIEW

**Comment by arthurp** [comment]
Updating conan works, but thrift fails to build on macOS. Maybe this is the sign that it's time to really drop macOS. https://github.com/KatanaGraph/katana/pull/261/checks?check_run_id=2707487664#step:7:2157

We could theoretically, pin the version of thrift instead of doing all this (arrow probably has a >= bound on the version which let it update). But that will only defer the problem until we are later forced to upgrade. So I would recommend doing it now and dropping macOS support if we need to. We have been talking about it for a while.

**Review by gliga — APPROVED** [review]
I like the proposed steps. Unless somebody that uses Katana also uses (or plans to use soon) MacOS, dropping it at this point seems reasonable. Once needed, it can be enabled one way or the other. It will also speed up CI ;)

**Review by ddn0 — APPROVED** [review]
I believe 1.37 is available at the moment.

**Comment by arthurp** [comment]
I'll make another PR for 1.37. I want this merged now to unblock other PRs.

**Pull request merged**
