### PR TITLE
Improve version scripts

### PR DESCRIPTION
**Pull request by arthurp**

### CODE REVIEW

**Comment by DataBoyTX** [comment]
Suggestions:  (putting all my notes in here that are related to this process and not necessarily just the typos this PR addresses, just to make sure they are captured) 

- consider adding the --really flag to the instructions here:  docs/contributing/releases.rst
- and/or add something at the end of the dry run output like:  WARNING: this was only a dry-run add --really switch to run the commands above  (because the first time I ran it it was not obvious it was only a dry run, I was following the steps in releases.rst 

- seems like everytime I ran it, I saw this warning.  Is this part of the normal operation of the script that would not impact the user?  if yes, then consider removing it, the wording "something failed"  makes me think something is broken or not set up correctly and I need to investigate, but there's little to go on.    
WARNING:__main__:Something failed. Reattempting after fetching the upstream remote.

- as part of the process I followed that you suggested, I got the following: 
$ scripts/version update_dependent_pr 1938
WARNING:__main__:Something failed. Reattempting after fetching the upstream remote.
ERROR(NotImplementedError): update_dependent_pr only supports single commit PRs. (It could be implemented if needed.)

Is it needed?  Was what I was doing requiring multiple commits, or was that a mistake on my part? 

- Trying to merge 1939:  Why am I getting this error about "not a valid object name origin/v0.1.99"?  And can we add a bit more detail about what $BRANCH and $BRANCH should be?  is that info available in the script where it colud print out the actual command that needs to be run? e.g. scripts/check_submodule_commit.sh external/katana release/v0.1.99 bump/v0.1.99rc1  
(or whatever this needs to be). There's no usage or comments in the script so I am not sure what the parameters should be. I see: $1, $2, and $3 are: 	
SUBMODULE_PATH=${1%/}
REQUIRED_SUPER_BRANCH=$(basename ${2:-master})
REQUIRED_SUB_BRANCH=$(basename ${3:-master})

but I am not sure what the SUPER_BRANCH and SUB_BRANCH are in this context. 


	Run scripts/check_submodule_commit.sh external/katana $BRANCH $BRANCH
	  scripts/check_submodule_commit.sh external/katana $BRANCH $BRANCH
	  shell: /usr/bin/bash -e {0}
	  env:
	    BRANCH: release/v0.1.99
	fatal: Not a valid object name origin/v0.1.99
	Error: Process completed with exit code 128.


Let me know if you'd like me to create jiras for suggestions to improve any of the above.

**Review by DataBoyTX — APPROVED** [review]

**Comment by arthurp** [comment]
> * consider adding the --really flag to the instructions here:  docs/contributing/releases.rst
> 
> * and/or add something at the end of the dry run output like:  WARNING: this was only a dry-run add --really switch to run the commands above  (because the first time I ran it it was not obvious it was only a dry run, I was following the steps in releases.rst
> 

Addressed.

>     * seems like everytime I ran it, I saw this warning.  Is this part of the normal operation of the script that would not impact the user?  if yes, then consider removing it, the wording "something failed"  makes me think something is broken or not set up correctly and I need to investigate, but there's little to go on.
>       WARNING:**main**:Something failed. Reattempting after fetching the upstream remote.

Addressed. It's possible it wasn't a real concern.

**Comment by arthurp** [comment]
>     * Trying to merge 1939:  Why am I getting this error about "not a valid object name origin/v0.1.99"?  And can we add a bit more detail about what $BRANCH and $BRANCH should be?  is that info available in the script where it colud print out the actual command that needs to be run? e.g. scripts/check_submodule_commit.sh external/katana release/v0.1.99 bump/v0.1.99rc1
>       (or whatever this needs to be). There's no usage or comments in the script so I am not sure what the parameters should be. I see: $1, $2, and $3 are:
>       SUBMODULE_PATH=${1%/}
>       REQUIRED_SUPER_BRANCH=$(basename ${2:-master})
>       REQUIRED_SUB_BRANCH=$(basename ${3:-master})
> 
> 
> but I am not sure what the SUPER_BRANCH and SUB_BRANCH are in this context.
> 
> ```
> Run scripts/check_submodule_commit.sh external/katana $BRANCH $BRANCH
>   scripts/check_submodule_commit.sh external/katana $BRANCH $BRANCH
>   shell: /usr/bin/bash -e {0}
>   env:
>     BRANCH: release/v0.1.99
> fatal: Not a valid object name origin/v0.1.99
> Error: Process completed with exit code 128.
> ```
> 
> Let me know if you'd like me to create jiras for suggestions to improve any of the above.

Documented in: https://github.com/KatanaGraph/katana-enterprise/pull/1998

**Comment by arthurp** [comment]
>     * as part of the process I followed that you suggested, I got the following:
>       $ scripts/version update_dependent_pr 1938
>       WARNING:**main**:Something failed. Reattempting after fetching the upstream remote.
>       ERROR(NotImplementedError): update_dependent_pr only supports single commit PRs. (It could be implemented if needed.)
> 
> 
> Is it needed? Was what I was doing requiring multiple commits, or was that a mistake on my part?

This is probably an issue on your end. I'm not sure. If it happens again, let's debug it in detail. I need to know your exact state.

**Comment by DataBoyTX** [comment]
Thanks @arthurp!!

**Pull request merged**
