### PR TITLE
Fix TOC to only put border on the lowest active element

### PR DESCRIPTION
**Pull request by JamesFCoffey**
Improvement to the TOC from High Seas.

### CODE REVIEW

**Comment by bobdc** [comment]
Is there an HTML demo of this change that we can see somewhere?

**Comment by JamesFCoffey** [comment]
> Is there an HTML demo of this change that we can see somewhere?

@bobdc Here you go.

**Currently:**
toc_current

**This PR:**
toc_new

**Comment by JamesFCoffey** [comment]
Keep in mind for the first image, it is of docs.k9h.dev and thus has more tabs than this `katana` repo.

**Review by bobdc — APPROVED** [review]
Looks good. Good idea.

**Comment by JamesFCoffey** [comment]
Due to conversion of `katana` to a subtree. This has been reopened here: https://github.com/KatanaGraph/katana-enterprise/pull/3761

**Pull request closed without merging**
