### PR TITLE
support: Provide accessors to CommBackend fields

### PR DESCRIPTION
**Pull request by ddn0**
Begin the refactor away from direct field access.

### CODE REVIEW

**Review by arthurp — APPROVED** [review]
Can you mark the fields deprecated and then suppress the warnings in the accessor methods? Might be a good idea. Though it's not required.

**Review by roshandathathri — APPROVED** [review]
Thanks!

**Comment by ddn0** [comment]
> Can you mark the fields deprecated and then suppress the warnings in the accessor methods?

You can do the first but I don't think there is a way to do the second.

**Comment by arthurp** [comment]
> > Can you mark the fields deprecated and then suppress the warnings in the accessor methods?
> 
> You can do the first but I don't think there is a way to do the second.

Aren't there local warning suppression pragmas? But anyway, this can all be later.

**Pull request merged**
