### PR TITLE
Remove unused scripts

### PR DESCRIPTION
**Pull request by ddn0**
- rename_galois_to_katana.sh is a one-off script to automate a refactor.
- abelian*, galois*, *lonestar* relate to a previous incarnation of this
  repo as a set of benchmarks
- *vtune* is a set of small scripts for converting the output of the
  rarely used vtune profiler

### CODE REVIEW

**Review by arthurp — APPROVED** [review]

**Comment by roshandathathri** [comment]
I'm a bit hesitant to delete `*_log_parser`, unless we're going to deprecate our `statsFile` printing completely.

**Comment by ddn0** [comment]
> I'm a bit hesitant to delete `*_log_parser`, unless we're going to deprecate our `statsFile` printing completely.

I do think we should move away from statsFile eventually in favor of structured logging, but I don't mind keeping the `*log_parser` around for now. I do wonder if these scripts have bit-rotted already though because the fields and such may have changed enough that no one can use these scripts without editing them anyway.

And AFAIK, even when [we] are actively benchmarking stuff, these scripts don't play much of a role in anyone's analysis flow.

I'll let you make the deciding vote though.

**Comment by roshandathathri** [comment]
> I'll let you make the deciding vote though.

I'll let @gurbinder533 make the deciding vote on that. Passing the buck :)

**Comment by gurbinder533** [comment]
I am in favor of deleting these scripts. As @ddn0 mentioned, no one can really use these without editing as things are constantly evolving.

**Review by gurbinder533 — APPROVED** [review]

**Review by roshandathathri — APPROVED** [review]
Thanks!

**Pull request merged**
