### PR TITLE
Tweak CI settings

### PR DESCRIPTION
**Pull request by ddn0**
Turning this testing PR into some reproducible value but printing out some ccache statistics and reducing the time we spend in testing sanitizer builds.

### CODE REVIEW

**Comment by arthurp** [comment]
You might want to call `ccache -z` to zero out the stats before you build. Otherwise your stats may be poluted by the ccache behavior during the run the generated the loaded ccache data.

BTW, I'm not totally sure ccache is working for conda, I just hadn't got around to debugging it. I wonder if we should have `ccache -z/-s` calls by default in all the builds that use ccache so it's easy to check if the ccache is working and how much gain we are getting.

**Comment by ddn0** [comment]
> I would recommend setting the maximum number of cached files to something on the order of the number of files compiled during the build. So maybe, for C++ builds `ccache -F 300` (set cache size in files to 300), for conda 100, and for gpu 2000. It might also be a good idea to run `ccache -c` at the end of the build. This will make sure the cache is cleaned up before it is stored away.

Seems like a reasonable change to me. It is annoying that we have to manually tweak this, but the performance anomalies when we don't seem worse than having stale ccache settings.

**Comment by arthurp** [comment]
It looks like the Conda build is cache missing really badly. Maybe I was overly aggressive and the caches need more space to hold a few different versions of the build. Maybe conda needs 250 or 300 files instead of 100. I see you increased the other tasks similarly.

**Comment by ddn0** [comment]
I bumped all the max file limits a bit from your original suggestions because I was seeing very low cache hit rates. There might be some edge case about ccache object replacement policies? Anyway, now, doing a simple rebuild (from a warm cache) gets > 90% hit rate, except for conda builds. This seems reasonable enough.

I didn't look into conda builds too deeply since the don't take a long time and the main point of this change is to keep caches bounded to give predictable behavior.

**Pull request merged**
