### PR TITLE
Update input version for mining tests

### PR DESCRIPTION
**Pull request by bowu**

### CODE REVIEW

**Review by arthurp — CHANGES_REQUESTED** [review]
I don't think the bliss deps belong in the open repo. It's not used here.

**Comment by bowu** [comment]
> I don't think the bliss deps belong in the open repo. It's not used here.

I only added it to the enterprise repo before. You asked me to follow `contribute.md` to add dependencies. Could you let me know what I should do in this case? Thanks.

**Comment by bowu** [comment]
> I don't think the bliss deps belong in the open repo. It's not used here.

I guess I read the wrong document. Let me fix this later.

**Comment by arthurp** [comment]
I suspect CONTRIBUTING.md isn't clear. The simple rule is, add dependencies in the repo that requires them, or just in open if they are required by both.

**Review by arthurp — APPROVED** [review]

**Pull request merged**
