### PR TITLE
Exposed katana library version in the Python API

### PR DESCRIPTION
**Pull request by Abhiramkns**

### CODE REVIEW

**Comment by arthurp** [comment]
Thanks so much for the PR. Welcome to the Katana open-source project. I'm guessing this PR is in response to issue #123. 

I'm aware you closed the PR, but I'm responding here for future reference. For you, if you want to work more on the PR or if others wish to try their hand at solving the above issue.

The approach used in 3784d0430905e5970c063284d4aa621c47fb254c, will not work because `scripts` is not available at run time. The best approach, I think is to use the C++ function `katana::GetVersion` from `katana/Version.h`. This returns the version as a string (which is what we need) and has no additional runtime dependencies since it's built into `libkatana_galois`. Wrappers for other functions from this file in a `katana.version` module might also be useful down the road, so I would encourage that.

https://github.com/KatanaGraph/katana/blob/d8dd4c3b5b42ae62927ae4576e1477aa800b67b9/libgalois/include/katana/Version.h#L29-L34

It might also be useful to embed the version information explicitly in the Python modules (in a generated `_version.py` or something), so as to have an independent katana-python version that can be checked against the `libkatana_galois` version to make sure the installation is correct and the library versions of compatible. That is secondary however.

**Comment by Abhiramkns** [comment]
When I'm trying to import katana library in the python API, I'm getting an ModuleNotFoundError: No module named 'katana.galois' in the __init__.py file. How to solve it?

**Comment by arthurp** [comment]
How are you building Katana? How are you launching the Python interpreter? I suspect your `PYTHONPATH` is not set correctly or Katana is not built correctly.

**Comment by Abhiramkns** [comment]
To build katana I followed the instruction given in the CONTRIBUTING.md file.

**Comment by arthurp** [comment]
Those instructions are for C++. Please try with the instructions from [Python.md](https://github.com/KatanaGraph/katana/blob/master/Python.md#building-katana-python). Currently, the Python API is only tested in Conda using solely Conda dependencies.

**Pull request closed without merging**
