### PR TITLE
Partially fix katana-enterprise GPU build

### PR DESCRIPTION
**Pull request by srogatch**

### CODE REVIEW

**Review by arthurp — APPROVED** [review]
LGTM. C++ compilers are such a confusing mess.

**Comment by srogatch** [comment]
> LGTM. C++ compilers are such a confusing mess.

Thanks for looking into it. It's `nvcc` that causes the most trouble. Before CUDA 11 it didn't even support C++17.

**Comment by arthurp** [comment]
We are actually C++ 14 compliant I think. This particular implicit conversion issue seems to be an issue though. AppleClang also has issues with these conversions, but different ones. Sigh. Oh well.

**Comment by srogatch** [comment]
No, we aren't: we use things like `is_convertible_v` which are C++17 https://en.cppreference.com/w/cpp/types/is_convertible . That's why we had to update CUDA to 11.x

**Comment by amberhassaan** [comment]
Just for my understanding: how do these cases arise? Is it when a .cu file includes a .h file that has such an implicit conversion?

**Comment by srogatch** [comment]
> Just for my understanding: how do these cases arise? Is it when a .cu file includes a .h file that has such an implicit conversion?

Yes. An alternative would be to split non-CUDA header files into pieces that can be included in CUDA and that cannot.

**Pull request merged**
