### PR TITLE
Improve Arrow/ImportData interchange

### PR DESCRIPTION
**Pull request by witchel**
Make it easier to go from Arrow format to our ImportData format which is mutable.

Look Ma, I wrote a function that takes two template arguments.  ~~But if someone can tell me how to rewrite it so that katana::ImportDataType::kTimestampMilli doesn't have to be such a special case, I will change it.~~ Nvm.  Changed it.

OpLog has moved to libgluon.

### CODE REVIEW

**Comment by witchel** [comment]
Adding @scober and @yige-hu as reviewers because I'd like to check this in today.

**Review by danielmawhirter — APPROVED** [review]
Ok, I have several (possibly stupid) questions, but none of them are specifically concerns about these changes, which LGTM.
1) Where do we use `ArrowToImport`? I don't see any instance of it being called in this repo.
2) Why does the ImportData struct exist in the first place? It appears to be a more limited version of arrow::Scalar in concept. Maybe this is a hammer looking for a nail, but I believe a visitor in the style of https://github.com/KatanaGraph/katana-enterprise/blob/master/libquery/include/katana/query/ArrowTypes.h (VisitArrowScalar), or some work on the Builder side, could make it unnecessary.

**Comment by witchel** [comment]
Thanks for the questions!

> Ok, I have several (possibly stupid) questions, but none of them are specifically concerns about these changes, which LGTM.
> 
> 1. Where do we use `ArrowToImport`? I don't see any instance of it being called in this repo.

I call it in my log ingest code which is to be checked in from the enterprise repo (#794).

> 2. Why does the ImportData struct exist in the first place? It appears to be a more limited version of arrow::Scalar in concept. Maybe this is a hammer looking for a nail, but I believe a visitor in the style of https://github.com/KatanaGraph/katana-enterprise/blob/master/libquery/include/katana/query/ArrowTypes.h (VisitArrowScalar), or some work on the Builder side, could make it unnecessary.

This is the conversation I wanted to have.  I need a mutable format for data during log ingesting.  My understanding is that arrow is not mutable, so while its type system is sufficient, its representation would be highly ineffecient.  Patrick developed ImportData for bulk conversion, and it fits the bill for mutability.  But I recognize that I'm elevating its importance and possibly tying us to greater support in the future replicating arrow types in ImportData.  I don't know of better alternatives, so I'm suggesting this course, but if there is a type-variable mutable format that is better then ImportData, let's use that.

**Comment by danielmawhirter** [comment]
By Arrow convention, Arrays (and the buffers they own) are indeed immutable. I might propose the following strategy:

- For fixed-size types (primarily POD), we can break the convention
  - An atomic update to the single data element, plus the null bitmap if necessarily, is probably doable. If this doesn't work, resort to the below.
- For general types, we obey the convention, but change the identity of the property array
  - Hot Update: Take Slices of the array from [0, index) and another from (index, end), which incur no buffer copies, Construct another array containing only the new data element. Construct a chunked array with the new element spliced between.
  - Cold Update: At some point later, flatten the chunks back into a single array, try to keep the total chunk count relatively low.
  - Only atomic operation required is to update the ChunkedArray that a property refers to.

My understanding is that the current approach incurs a whole-property copy from arrow->InputData, then another from InputData->arrow on each property update. As long as the code could be re-worked to support ChunkedArray in general, those mandatory copies could be avoided. Note that the Cold update is still only one copy instead of 2. Does this make sense?
[Writing Arrow.pptx](https://github.com/KatanaGraph/katana/files/5860880/Writing.Arrow.pptx)

**Comment by witchel** [comment]
> By Arrow convention, Arrays (and the buffers they own) are indeed immutable. I might propose the following strategy:
> 
> * For fixed-size types (primarily POD), we can break the convention
>   
>   * An atomic update to the single data element, plus the null bitmap if necessarily, is probably doable. If this doesn't work, resort to the below.
> * For general types, we obey the convention, but change the identity of the property array
>   
>   * Hot Update: Take Slices of the array from [0, index) and another from (index, end), which incur no buffer copies, Construct another array containing only the new data element. Construct a chunked array with the new element spliced between.
>   * Cold Update: At some point later, flatten the chunks back into a single array, try to keep the total chunk count relatively low.
>   * Only atomic operation required is to update the ChunkedArray that a property refers to.
> 
> My understanding is that the current approach incurs a whole-property copy from arrow->InputData, then another from InputData->arrow on each property update. As long as the code could be re-worked to support ChunkedArray in general, those mandatory copies could be avoided. Note that the Cold update is still only one copy instead of 2. Does this make sense?
> [Writing Arrow.pptx](https://github.com/KatanaGraph/katana/files/5860880/Writing.Arrow.pptx)

These are great ideas!  Allow me two meta comments first.

1. I will copy some of this discussion into RFC-007, which is about log ingest.

2. Is it worthwhile to create a slack channel for Arrow discussions?  It seems like there might be a critical mass of query/storage/networking interest and enough technical content to sustain such a discussion.

As far as your idea....maybe.  I'm traversing my log entries and I come across a write.  Ok, I create a chunked array.  Then that entry is written again.  Can I update the chunked array?  Doing it this way means I am allocating an entry at a time and doing non-trivial calculations to created chunked arrays for each update.  Right now I create a vector of ImportData and each assignment is pretty trivial.

**Pull request merged**
