### PR TITLE
[KAT-623] python: Refactor open-source API into katana.local mostly.

### PR DESCRIPTION
**Pull request by arthurp**
With: https://github.com/KatanaGraph/katana-enterprise/pull/1660

The following were moved into `katana.local`:

* PropertyGraph (property_graph.py, _property_graph.pxd, _property_graph.pyx, _property_graph_numba.pyx.jinja)
* Atomic operations on numpy arrays (atomic.pyx.jinja)
* Barrier and friends (barrier.pxd, barrier.pyx)
* InsertBag and LargeArray (datastructures.pxd.jinja, datastructures.pyx.jinja)
* Dynamic Bitset (dynamic_bitset.pxd, dynamic_bitset.pyx)
* Non-property Graphs (graphs.instantiations.jinja, graphs.pxd.jinja, graphs.pyx.jinja)
* The katana.analytics package.

`katana.example_utils` was renamed to `katana.example_data`. `katana.utils` and `katana.numba_support` where combined (with a couple other stray modules) into `katana.native_interfacing`.

These changes touch a *lot* of files, but are very mechanical. I did not make any code changes other than those required to make the new module/package layout work.

### CODE REVIEW

**Comment by arthurp** [comment]
@gliga I mainly want you to look at the list of changes in the description. The changes themselves are boring and mechanical, don't feel like you should really read them. A few spot checks wouldn't hurt, but I know you are busy.

@denish44 This is fairly mechanical, so deep API knowledge is not needed, I just want more people to spot check things.

**Review by denish44 — APPROVED** [review]

**Comment by denish44** [comment]
This looks good at a glance, mainly just refactoring. I did notice the pipeline is skipping some steps, is that okay?

**Comment by arthurp** [comment]
I skipped then intentionally. I cannot merge without them though. I'll run full ci before merging.

**Review by gliga — COMMENTED** [review]
LG!

**Pull request merged**
