### PR TITLE
lonestar: process arguments before galois init

### PR DESCRIPTION
**Pull request by tylershunt**
Since our arg handler helpfully tears everything down  when arg parsing
fails or when `--help` is requested do that before we initialize galois.

For dist apps initializing galois also initializes MPI which then
segfaults when the arg parser ends the program in an unsupported way.
Simply switching the order prevents it from segfault-ing.

Signed-off-by: Tyler Hunt <thunt@katanagraph.com>

### CODE REVIEW

**Review by ddn0 — APPROVED** [review]
This is also true of the non-distributed applications though I suppose it matters less.

**Review by gurbinder533 — APPROVED** [review]

**Comment by tylershunt** [comment]
> This is also true of the non-distributed applications though I suppose it matters less.

I'll change them as well to be consistent.

**Review by roshandathathri — APPROVED** [review]
Great!

**Comment by tylershunt** [comment]
I decided to return a `unique_ptr` to the appropriate Galois system object since that seems more maintainable than expecting these things to be done in the proper order.

**Pull request merged**
