### PR TITLE
cmake: Add a config option to call conan in the way we expect

### PR DESCRIPTION
**Pull request by tylershunt**
A patch born of my own sloth.

I found this very nice cmake include for conan:
`https://github.com/conan-io/cmake-conan`

I added it here and call it if `-DGALOIS_AUTO_CONAN=on` is passed to
cmake at config time. `-DCMAKE_TOOLCHAIN_FILE` is not needed in this
mode.

It has the nice effect of calling conan every time cmake is run. So if
new dependencies are added to config/conanfile.txt they will be installed
automatically when `cmake` is re-run because some `CMakeLists.txt` was
updated.

I tested it by blowing away `build` and running:
`cmake -DGALOIS_AUTO_CONAN=on -DGALOIS_ENALBE_DIST=on`

I also tested by switching to @ddn0's libsuport branch (which adds
the `libfmt` dependency) and ensuring that I was able to 'just build'
without having to invoke conan on my own.

Signed-off-by: Tyler Hunt <thunt@katanagraph.com>

### CODE REVIEW

**Comment by tylershunt** [comment]
I think a valid question to ask before merging is "Will anyone use this but Tyler?" It's not that much more complicated to just run `conan install -if $HOME/build --build=missing config` when you see the build fail because you're missing some library, but even to write this comment I had to look that up which is why I started looking into alt config paths in the first place.

The people most suited to answer this question are people like @witchel @bowu and simon (will edit with simon's github tag). Since they are people that have had to adapt to our tools relatively recently.

I'll collect an informal poll here to get the general temperature: 👍 if you would use this 👎 if you think it's needless cruft.

**Comment by l-hoang** [comment]
As someone who hasn't tried out the conan build yet, if it makes my life easier I'm for it. (can't comment on how this would make my life easier since I'm unfamiliar with how conan works, but from a quick glance it seems like it makes it so I don't have do something if there's a dependency update).

**Comment by bowu** [comment]
I think it's useful, especially because I had to check the document several times for just this command recently.

**Comment by tylershunt** [comment]
That's enough support for me! I'll merge it.

**Pull request merged**
