### PR TITLE
enable ArrowVisitor on arrow::NullType

### PR DESCRIPTION
**Pull request by danielmawhirter**
Correctly handling NullType allows for typeless-nulls, like the Cypher `null` keyword.
A Scalar (`std::shared_ptr<arrow::Scalar>`) can be verified to be null in several ways:
`scalar->type->Equals(arrow::null())` (typeless null)
`scalar->type->id() == arrow::Type::NA` (typeless null)
`dynamic_cast<arrow::NullScalar*>(scalar.get()) != nullptr` (typeless null)
`scalar->is_valid == false` (possibly typed null)

### CODE REVIEW

**Comment by danielmawhirter** [comment]
Resolves #10 while I'm here, json_checker moved to enterprise a while ago

**Comment by danielmawhirter** [comment]
Relevant to #25

**Review by witchel — APPROVED** [review]
The code looks fine, but are we generating the typeless nulls?  Because in GraphUpdate I always generate null's using the property schema type.

**Comment by danielmawhirter** [comment]
> The code looks fine, but are we generating the typeless nulls? Because in GraphUpdate I always generate null's using the property schema type.

Up to this point we haven't, partially due to this limitation. Query has a use case that wants them now though (Cypher `null` keyword), so IMO it's time to enable them

**Pull request merged**
