### PR TITLE
querytest CI fixes

### PR DESCRIPTION
**Pull request by l-hoang**
Marks the verify test as quick so it can run in CI and also adds
fixtures so that verify does not run before run if run in parallel.

In addition, removes the use of char* for strings in CypherCompiler
and replaces them with std::strings; they were causing memory
leaks, and rather than fix the leaks it was better to just replace
everything with a std::string which handles it for us.

### CODE REVIEW

**Comment by l-hoang** [comment]
Looks like verification failed because the verify files weren't found. It seems that they're running in the correct order at least.

@ddn0 thoughts/help?

**Comment by l-hoang** [comment]
Seems like there's a mismatch between what happens when I pass "n" threads and the number that actually gets used:

The 8 thread test passes -t=8, but it outputs with t2 because only 2 threads actually run; the output file name is currently based on the numThreads var which gets set to 2 for some reason.

Screen Shot 2020-07-17 at 7 17 17 PM

**Comment by ddn0** [comment]
>  the output file name is currently based on the numThreads var which gets set to 2 for some reason.

The CI machines only have two cores.

**Comment by l-hoang** [comment]
> > the output file name is currently based on the numThreads var which gets set to 2 for some reason.
> 
> The CI machines only have two cores.

That explains much. Guess I'll limit it to 2 for now.

**Comment by l-hoang** [comment]
Sanitizer failure fix is something I've already TODO'd; will get on it next week.

**Comment by l-hoang** [comment]
Fixed the memory leak by removing the "new" calls occurring in the first place and added @roshandathathri as a reviewer since there are now code changes.

**Pull request merged**
