### PR TITLE
Rename dist.IsLocal to dist.HasProxy

### PR DESCRIPTION
**Pull request by ddn0**
IsLocal checks to see if the global ID has a corresponding local ID.
This can be confused for a separate but different query, is the given ID
a local ID or a global one. Rename IsLocal to be more clear about what
it is checking.

### CODE REVIEW

**Review by gurbinder533 — APPROVED** [review]
LGTM.

**Comment by roshandathathri** [comment]
Didn't like the new name. How about `HasProxy` or `HasLocalProxy`? `Proxy` or `Replica` - either is fine.

**Comment by roshandathathri** [comment]
Closing as this will be fixed in #540

**Comment by ddn0** [comment]
Went with `HasProxy` since proxy seems to be used more frequently.

**Review by roshandathathri — APPROVED** [review]
Thanks!

**Pull request merged**
