### PR TITLE
tsuba: [wip] integrate zookeeper client library

### PR DESCRIPTION
**Pull request by tylershunt**
Trying to socialize these build ideas and get early feedback. The
zookeeper client library is not available through conan or any standard
package manager for ubuntu as far as I can tell, although it is
available through conda-forge.

I use CMake FetchContent to download zookeeper from the official repo
(selecting the version that is in conda-forge). I then apply a patch
which tweaks CMakeLists.txt in the sub-project so that it can be built
by our build system as a sub_directory.

You'll notice that the patch also adds a couple files; these are files
that are deterministically generated based on the zookeeper source but
not checked in. I thought that having kind of a large patch was better
than forcing `ant` to be installed everywhere we want to build.

I also packaged my `FetchContent`->`Patch`->`add_subdirectory` workflow
into a cmake function and reuse it to build the azure sdk.

Signed-off-by: Tyler Hunt <thunt@katanagraph.com>

### CODE REVIEW

**Comment by arthurp** [comment]
I know this is WIP, but I wanted to verify that in conda builds we will use the conda package instead of the fetch/.../build flow. Maybe you could have cmake check for zookeeper and then only fetch and build if it's not available. Then we can add zookeeper to the conda package dependencies (and the conda development environment description).

**Comment by tylershunt** [comment]
> I know this is WIP, but I wanted to verify that in conda builds we will use the conda package instead of the fetch/.../build flow. Maybe you could have cmake check for zookeeper and then only fetch and build if it's not available. Then we can add zookeeper to the conda package dependencies (and the conda development environment description).

I was actually curious about this, does it matter if libzookeeper is always statically linked? because that's the only build mode supported via cmake.

**Comment by arthurp** [comment]
I would prefer to use the external (conda-forge) build of libzookeeper even if it's statically linked. The less we roll ourselves, the better, in my book. There are two reasons:

1. If we use the packaged version and it is dynamically linked it will make our libgalois more compatible with other libraries (that could be loaded in parallel into a C++ or Python application). Specifically if the application is directly accessing libzookeeper, it's probably better to have a single instance of it.
2. If we use the packaged version we don't have to do as much work to make things work with new and improved versions of zookeeper. And avoiding version tracking work seems good.

**Comment by tylershunt** [comment]
Yeah you're right this whole thing ends up being a fragile mess no matter how you slice it. I'm going to do something different.

**Pull request closed without merging**
