### PR TITLE
Add conversions so that libtsuba works with AWS SDK in all cases.

### PR DESCRIPTION
**Pull request by arthurp**
AWS SDK is sometimes configured to use a custom allocator that makes Aws::String incompatible with std::string. This patch adds conversions so that libtsuba correctly handles any allocator configuration.

### CODE REVIEW

**Comment by arthurp** [comment]
1. I think I'll leave it as is for now because it makes the types very simple: Always use std::string and then convert at the last moment. We can change that later if needed, but it seems like it would make things more complex to have a mix of different string types within the module.
2. There will be a check for this in CI soon since I will be pushing a conda build CI step as soon as I have it ready. That will fail if strings are not converted correctly.

**Comment by tylershunt** [comment]
> 1. I think I'll leave it as is for now because it makes the types very simple
Cool beans. Thanks!

**Comment by witchel** [comment]
The branch I'm working on has a lot of these calls to S3.  Just so I understand, I think y'all are saying that I will be able to build if I just pass std::string to SetBucket, but I will fail the CI?

**Comment by arthurp** [comment]
Eventually, yes (though the changes to CI are not even started yet). I will investigate if there is a way to configure conan to build AWS SDK in a way that will match what we need for Conda. That kind of different between local build and CI is definitely a problem.

**Comment by tylershunt** [comment]
> I will investigate if there is a way to configure conan to build AWS SDK in a way that will match what we need for Conda.

Yeah having the build fail locally would be most idea.

**Pull request merged**
