### PR TITLE
conan: ditch libxml2; depend on system's version

### PR DESCRIPTION
**Pull request by tylershunt**
Signed-off-by: Tyler Hunt <thunt@katanagraph.com>

### CODE REVIEW

**Comment by tylershunt** [comment]
> Do we want to add a line in the setup_ubuntu script that will install the zlib library as well if we're going to depend on a system's zlib?

you got it.

**Comment by tylershunt** [comment]
Turns out selecting `zlib=False` was just triggering a re-build not really solving our problem. Seems fragile (i.e., if they ever add a non zlib version our builds will start to break).

**Comment by tylershunt** [comment]
I had to bump the `libxml2` version down to `9.4.1` (from `9.4.4`) to support the python packaging target. I'm assuming that's fine and that there's nothing from `libxml2-9.4.4` that we need (seems to build) but I thought I'd ping @patrickkenney9801 just in case that's not true.

**Comment by patrickkenney9801** [comment]
that should be fine, thanks for fixing this Tyler

**Pull request merged**
