### PR TITLE
Make threads a transitive dependency of galois

### PR DESCRIPTION
**Pull request by yshalabi**
cherry picking pthreads fix for release branch

### CODE REVIEW

**Review by roshandathathri — APPROVED** [review]
LGTM

**Comment by ddn0** [comment]
I think you'll need `external/katana` changes to fix the build as well.

**Comment by ddn0** [comment]
You might need e672f38f71d277ca598e5f6e90fa6f0e30b67a71 as well.

**Comment by yshalabi** [comment]
@ddn0 did you see `E   ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 232 from C header, got 216 from PyObject` when you were working on this?

**Pull request merged**
