### PR TITLE
Remove unused features in Gluon

### PR DESCRIPTION
**Pull request by ddn0**
After #500 

```
is_vector_bitset is not used as well as the dataSplit and dataSplitFirst
data modes.
```

### CODE REVIEW

**Comment by l-hoang** [comment]
this is a question to Roshan/Gurbinder:

why were sync structures static in the first place? so you could use them as templates?
if so, is there a performance difference?

**Comment by roshandathathri** [comment]
> why were sync structures static in the first place? so you could use them as templates?

Yes

> if so, is there a performance difference?

Hasn't been evaluated but it was assumed to be so. For this use case, the static functions (template functions) can be inlined but if objects are used, their functions cannot be inlined.

**Comment by ddn0** [comment]
> For this use case, the static functions (template functions) can be inlined but if objects are used, their functions cannot be inlined.

I don't know if that is strictly true. The only difference between a member function and a static function is the implicit "this" parameter. That additional field may affect code generation in many ways but it would surprise me that it would directly control inlining.

It is probably the case that passing an object down introduces argument passing code that can be omitted when making a static call. Though if that is a concern, we probably shouldn't be passing `loopName` everywhere either.

**Comment by roshandathathri** [comment]
> The only difference between a member function and a static function is the implicit "this" parameter. That additional field may affect code generation in many ways but it would surprise me that it would directly control inlining.

I don't disagree with you said here but I probably wasn't clear. The key difference is that the static function is a template argument, so in the specialized instantiation, it is likely to be inlined because the function itself is a couple of lines. This can impact performance because these functions are used within in tight loops, so the function call overhead can be high.

In any case, I'm not suggesting that we should continue using templates because they require global variables, which is a bad design.

Let's first get the non-global variables variant working. I can work on improving performance later if needed.

**Comment by roshandathathri** [comment]
> It is probably the case that passing an object down introduces argument passing code that can be omitted when making a static call. Though if that is a concern, we probably shouldn't be passing `loopName` everywhere either.

I don't think it's the argument passing overhead. I'm only concerned about the function call overhead (as stated above). 

I think there's a middle ground where we can pass the object(s) that needs to be synchronized as function arguments but use the "operation" for synchronization as a template parameter, thereby avoiding calling functions on the object (in tight loops). I can look into that later.

**Comment by roshandathathri** [comment]
This PR is doing what I wanted - using templates and avoiding global variables. I'm not concerned about the performance impact - it should be minimal. I was confused about possible solutions and specifically, this solution. So, some of my comments above may not make sense.

**Review by roshandathathri — APPROVED** [review]
This looks great!

**Review by gurbinder533 — APPROVED** [review]
LGTM

**Comment by ddn0** [comment]
> I'm not concerned about the performance impact - it should be minimal. I was confused about possible solutions and specifically, this solution. So, some of my comments above may not make sense.

I don't think there is a disagreement. I was mainly clarifying for @l-hoang . 

From my perspective, I think this change is performance-neutral, and if there happens to be a negative impact, I think we can resolve it while also keeping the non-static structure. I think your position might be a little more pessimistic (e.g., this change might be performance-negative), but in any event, both of us agree that we can fix it while still keeping the better non-static interface.

**Comment by roshandathathri** [comment]
> I think this change is performance-neutral

I think so too.

**Comment by l-hoang** [comment]
thanks for entertaining my questions!

**Pull request merged**
