### PR TITLE
BC level to array of structures

### PR DESCRIPTION
**Pull request by l-hoang**
Array of structures has more locality for fields, so this commit changes
it to that format for the node data.

### CODE REVIEW

**Comment by l-hoang** [comment]
Currently does not run: comes up with a no-such-property error.

**Comment by l-hoang** [comment]
Should now run.

**Comment by l-hoang** [comment]
Need to figure out how to get AoS to work with the GetNodePropertyTyped function.

**Comment by l-hoang** [comment]
Should work end to end now; BC tests pass locally.

**Review by roshandathathri — APPROVED** [review]
LGTM

**Pull request merged**
