### PR TITLE
update test-datasets

### PR DESCRIPTION
**Pull request by e-mcginnis**
new v3 rmat10/15_symmetric provided by analytics team

### CODE REVIEW

**Comment by e-mcginnis** [comment]
Barring merge behind enterprise PR passing CI

**Review by gliga — APPROVED** [review]
Looks good

**Comment by e-mcginnis** [comment]
looks like we need some new verify files to match the new symmetric rmat10/15 
```
The following tests FAILED:
	201 - verify-k-core-cpu.input=small.threads=2.args=--kCoreNumber=100-symmetricGraph--algo=Synchronous (Failed)
	205 - verify-k-core-cpu.input=small.threads=1.args=--kCoreNumber=100-symmetricGraph--algo=Synchronous (Failed)
	209 - verify-k-core-cpu.input=small.threads=2.args=--kCoreNumber=100-symmetricGraph--algo=Asynchronous (Failed)
	213 - verify-k-core-cpu.input=small.threads=1.args=--kCoreNumber=100-symmetricGraph--algo=Asynchronous (Failed)
```

**Review by tylershunt — APPROVED** [review]

**Comment by tylershunt** [comment]
> looks like we need some new verify files to match the new symmetric rmat10/15

@gurbinder533 any advice?

**Comment by e-mcginnis** [comment]
I reached out to @gurbinder533 out of band earlier and he said he'd look into it. So blocking this PR on new verify files.

**Comment by e-mcginnis** [comment]
Got new versions of the symmetric rdgs from @gurbinder533, the verify tests now pass locally.

**Comment by gliga** [comment]
thanks

**Comment by e-mcginnis** [comment]
@gurbinder533 seems `test_k_truss` expects a slightly different valud in rmat10_symmetric. Is this an error in the rdg, or the test? 
````
=================================== FAILURES ===================================
_________________________________ test_k_truss _________________________________

    def test_k_truss():
        graph = Graph(get_rdg_dataset("rmat10_symmetric"))
    
        k_truss(graph, 10, "output")
    
        stats = KTrussStatistics(graph, 10, "output")
    
>       assert stats.number_of_edges_left == 13338
E       assert 13339 == 13338
E         +13339
E         -13338
```

**Comment by gurbinder533** [comment]
> @gurbinder533 seems `test_k_truss` expects a slightly different valud in rmat10_symmetric. Is this an error in the rdg, or the test?
> 
> ```
> =================================== FAILURES ===================================
> _________________________________ test_k_truss _________________________________
> 
>     def test_k_truss():
>         graph = Graph(get_rdg_dataset("rmat10_symmetric"))
>     
>         k_truss(graph, 10, "output")
>     
>         stats = KTrussStatistics(graph, 10, "output")
>     
> >       assert stats.number_of_edges_left == 13338
> E       assert 13339 == 13338
> E         +13339
> E         -13338
> ```
> ```

I think I know what is wrong. I will fix it.

**Comment by e-mcginnis** [comment]
Thanks @gurbinder533, just running some enterprise tests that use these graphs. Once those pass I'll merge this.

**Comment by e-mcginnis** [comment]
all enterprise tests involving these graphs passed.

**Pull request merged**
