### PR TITLE
build: Cleanup libquery build

### PR DESCRIPTION
**Pull request by ddn0**
Follow patterns in other lib directories; avoid overlinking.

### CODE REVIEW

**Comment by l-hoang** [comment]
This is included in PR #154 (at least, in my local copy if it's not already there).

**Comment by ddn0** [comment]
Sweet! Looks good!

BTW, do you mind adding this bit too:
```
target_include_directories(galois_query PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
  $<INSTALL_INTERFACE:include>
)
```

This will make sure than if/when galois_query is installed as a library, its include directory reflects the installed path rather than the path in the source directory.

**Comment by l-hoang** [comment]
Ack'd. Will be part of the next force push (still locally debugging conda/python; thanks for the help with that!).

**Comment by ddn0** [comment]
Great minds think alike

**Pull request closed without merging**
