### PR TITLE
Rename Id to ID

### PR DESCRIPTION
**Pull request by ddn0**
Closes https://github.com/KatanaGraph/katana-enterprise/issues/1049

### CODE REVIEW

**Review by arthurp — APPROVED** [review]
May the search and replace be with you.

I didn't really check this. Did you just use a tool or was anything manual?

**Review by roshandathathri — APPROVED** [review]
Yay! Assuming it's not manual :P

**Comment by ddn0** [comment]
> I didn't really check this. Did you just use a tool or was anything manual?

I did a series of `grep`s to find uses of `Id` and then examined each case and updated them; in cases where there was a clear pattern, I did a search-and-replace.

**Review by tylershunt — APPROVED** [review]
LGTM

**Pull request merged**
