### PR TITLE
support: add `inline` to header defined functions

### PR DESCRIPTION
**Pull request by tylershunt**
Signed-off-by: Tyler Hunt <thunt@katanagraph.com>

### CODE REVIEW

**Comment by arthurp** [comment]
Which compiler is not inlining this? And do we really care?

**Comment by ddn0** [comment]
I'd guess it is not the inlining that we care about but the multiple visible definitions (on MacOS where we don't do `-fvisiblity=hidden`)?

**Comment by tylershunt** [comment]
> Which compiler is not inlining this? And do we really care?

I don't care about inlining at all, but it's needed to compile at all for static builds I think. I ended up in a situation where it was defined in my appliction `.o` and also in the archive for `libgluon` I could move them all to anonymous instead if you would like, but I added inline to match the style that was here.

**Comment by ddn0** [comment]
`inline` is fine by me.

**Review by ddn0 — APPROVED** [review]

**Review by witchel — APPROVED** [review]
Yeah, sorry, I think some of the functions in that file are inlined and it is completely a visibility thing.  I should have inlined them all from the start, and if we want one day we can put them in an object file and export them.

**Pull request merged**
