### PR TITLE
Add github workflow to enforce JIRA tag presence

### PR DESCRIPTION
**Pull request by e-mcginnis**
clearing description to test workflow

### CODE REVIEW

**Comment by arthurp** [comment]
How does this handle a case where someone uses a bunch of random commits on their branch then uses Squash and Merge (in the github UI) to merge it into master? It seems like this might force people to manually squash and then rerun CI.

**Comment by e-mcginnis** [comment]
> How does this handle a case where someone uses a bunch of random commits on their branch then uses Squash and Merge (in the github UI) to merge it into master? It seems like this might force people to manually squash and then rerun CI.

@arthurp this is one of the cases I am testing for. Still some WIP here to ensure cases like that aren't negatively impacted.

**Comment by arthurp** [comment]
Great. Just happened across this PR and had things thought. I like this change overall.

**Comment by e-mcginnis** [comment]
current issue I am observing with this:
1) start have one of many commits with a jira tag, workflow passes
2) amend the message to remove the jira tag, force push, workflow should fail
3) workflow still passes despite no commits in the PR having a jira tag

**Comment by e-mcginnis** [comment]
seems there are some interesting bugs in how github actions can access available commit messages in a PR, removing and re-adding the action and doing a squash/force push seems to have put this PR in a state where github doesn't pass any commit messages to the action. Closing & creating a fresh PR

**Pull request closed without merging**
