### PR TITLE
adding views to jaccard

### PR DESCRIPTION
**Pull request by amazloumi**

### CODE REVIEW

**Comment by uditagar** [comment]
same performance benchmarking required for this as well. Thanks

**Review by gurbinder533 — APPROVED** [review]
LGTM.

**Comment by uditagar** [comment]
Do not commit this to master until we are sure that there is no change in total/execution time with respect to `master`.

**Review by uditagar — APPROVED** [review]
This is good to go. seems there are no performance issues with Default views, it seems.

**Pull request merged**
