### PR TITLE
Add functionality to handle self edges in shared memory triangle counting app

### PR DESCRIPTION
**Pull request by uditagar**
This PR adds the functionality to handle self edges in shared memory triangle counting app.

### CODE REVIEW

**Review by roshandathathri — APPROVED** [review]
Thanks!

Please test before merging

**Review by amazloumi — APPROVED** [review]
seems fine to me.

**Comment by uditagar** [comment]
output after change: 

`NumTriangles: 48260
`
matches the required count

**Comment by roshandathathri** [comment]
> output after change:
> 
> `NumTriangles: 48260 ` matches the required count

Great, thanks!

**Pull request merged**
