### PR TITLE
Patch GRPC to avoid gettid build failure

### PR DESCRIPTION
**Pull request by ddn0**
After #106

### CODE REVIEW

**Comment by yuhc** [comment]
Are you able to build libava with this patch? (It only patches the gRPC in Katana, and I may also apply this patch to the gRPC in AvA as well.)

**Comment by ddn0** [comment]
> Are you able to build libava with this patch

The CI builds and it builds locally. Is there something else I should test to confirm that everything is ok?

**Comment by yuhc** [comment]
> The CI builds and it builds locally. Is there something else I should test to confirm that everything is ok?

AvA builds a same gRPC as libava(/manager) does. It's interesting if it works with only one gRPC patched.
Without this patch, Did libava fail to build gRPC but the cloned AvA succeed to build it?

**Comment by ddn0** [comment]
My previous build directory was dirty.

Retested from a clean build and verified that the build is successful (where previously I would get the gettid issue).

**Pull request merged**
