### PR TITLE
Fix handling of backward 1.6 conda package

### PR DESCRIPTION
**Pull request by arthurp**
The upstream conda package put the cmake config file in the wrong place (lib64 instead of lib). This just checks that path to find it.

JIRA: KAT-1427

### CODE REVIEW

**Review by amberhassaan — APPROVED** [review]
Thanks.

**Comment by witchel** [comment]
Super cool.

**Comment by witchel** [comment]
I wait with bated breath.  I mean that as encouragement!

**Comment by witchel** [comment]
> I wait with bated breath. I mean that as encouragement!

Hmm, I misspelled this as "baited" breath.  I didn't realize it is bated as in abated as in short of breath.

**Comment by arthurp** [comment]
hehehe. It is. Baited breath begs the questions, baited for what?

**Comment by witchel** [comment]
> hehehe. It is. Baited breath begs the questions, baited for what?

I thought it was one of those "references antiquated concepts in a way that no longer completely makes sense" sort of expressions.  I think "hell-bent for leather" is one of those.

**Comment by arthurp** [comment]
My favorite is to "let the cat out of the bag".

**Pull request merged**
