### PR TITLE
Rename dynamic bitset file to match class

### PR DESCRIPTION
**Pull request by ddn0**
Fix a small but unexpected case difference where galois::DynamicBitSet
is defined in a file named DynamicBitset.h.

### CODE REVIEW

**Comment by roshandathathri** [comment]
FWIW I prefer DynamicBitset to DynamicBitSet, that is I prefer to change the class name than the file name.

Note that we have a similar class for cuda as well, which uses DynamicBitset for both class and file name. 

On a related note, boost has a similar class but that does not support concurrent types, which is why I implemented a new class. 
https://theboostcpplibraries.com/boost.dynamicbitset
Boost uses dynamic_bitset for the class name.

Finally, I think the name bitvector is more precise than bitset but both STL and boost use bitset to denote, so I went with that term.

**Review by roshandathathri — APPROVED** [review]
The cuda class DynamicBitset is inconsistent with the rest.

**Comment by ddn0** [comment]
> FWIW I prefer DynamicBitset to DynamicBitSet, that is I prefer to change the class name than the file name.

I like DynamicBitset better as well.

I've updated everything to match, including the cuda data structure.

**Review by gurbinder533 — APPROVED** [review]
+1 for DynamicBitset.

**Pull request merged**
