### PR TITLE
Clarify output of jeon-checker, update for new output path approach

### PR DESCRIPTION
**Pull request by danielmawhirter**

### CODE REVIEW

**Comment by danielmawhirter** [comment]
This change only affects querying in the enterprise repo, and the json checker is only used there. I'm now planning to remove the file from the open repo, and make this change there instead.

**Comment by arthurp** [comment]
This script isn't at all specific to query results (it looks to work on any JSON) and I wouldn't think it will change much, so I'd prefer to leave it here.

**Comment by danielmawhirter** [comment]
The way it's set up for file paths is dependent on things in querying, namely graph-query.cpp, the CMakeLists.txt in the same directory, and the query-specific inputs. Hopefully it will be relatively stable, but so far ~25% of my PRs touch this file.

You're right, that the comparison approach could work for any json, it's just structurally pretty dependent.

**Comment by danielmawhirter** [comment]
Part of my reasoning is that no tests in this repo touch this file

**Comment by ddn0** [comment]
We also have `scripts/result_checker.py` which is like the line-oriented version of `scripts/json_checker.py`. If we are going to have JSON checking in this repo, can we also make a plan to eventually merge its functionality into a unified `result_checker.py`?

**Comment by danielmawhirter** [comment]
json_checker.py has been sensitive to changes in the enterprise repo recently, closing

**Comment by arthurp** [comment]
@danielmawhirter maybe next time you touch it rename it to `query_json_checker.py` or something. To make it clear that it's specialized for one purpose.

**Pull request closed without merging**
