### PR TITLE
Pybind11/Cython "integration"

### PR DESCRIPTION
**Pull request by arthurp**
This allows pybind11 and Cython to access and construct each others objects. The implementation has some performance issues (repeated python function calls), and it cannot be used within Numba compiled code.

### CODE REVIEW

**Comment by arthurp** [comment]
I pulled in changes to fix the CI issues based on https://github.com/KatanaGraph/katana/pull/809. I did *not* try to fix the build_in_container mistake that @ddn0 is trying to fix there. I'm just getting CI unblocked if possible. build_in_container does need to be fixed or removed.

**Comment by arthurp** [comment]
This PR unblocks CI. Please review.

**Review by ddn0 — APPROVED** [review]
LGTM

When you merge, can you update the message in 5016cecba1cf67d8107a2b6e95a480f0ddacd999 to be more self-contained as I'll probably just drop the same CI fixing changes in my PR and we don't want to have dangling references to obsolete work?

**Comment by arthurp** [comment]
> LGTM
> 
> When you merge, can you update the message in [5016cec](https://github.com/KatanaGraph/katana/commit/5016cecba1cf67d8107a2b6e95a480f0ddacd999) to be more self-contained as I'll probably just drop the same CI fixing changes in my PR and we don't want to have dangling references to obsolete work?

Of course, good point. Are you also implying you want me to "rebase" instead of squashing? I'm fine with that.

**Comment by ddn0** [comment]
> Of course, good point. Are you also implying you want me to "rebase" instead of squashing? I'm fine with that.

Rebase or squash doesn't matter to me as long as the message is reasonably correct :D

**Pull request merged**
