### PR TITLE
Cancel CI jobs if a new version of the PR is pushed.

### PR DESCRIPTION
**Pull request by arthurp**
This is applying the same changes as used in enterprise (https://github.com/KatanaGraph/katana-enterprise/commit/29fe27c6502da65157639fb72cbe2f514a69f553) in open.

### CODE REVIEW

**Comment by arthurp** [comment]
Cancellation seems to work fine. @ddn0 Is there any specific reason you didn't do this for the open repo before?

**Comment by ddn0** [comment]
> Cancellation seems to work fine. @ddn0 Is there any specific reason you didn't do this for the open repo before?

Mainly because it doesn't cost us anything to run CI jobs for open source projects in GitHub.

**Comment by arthurp** [comment]
> > Cancellation seems to work fine. @ddn0 Is there any specific reason you didn't do this for the open repo before?
> 
> Mainly because it doesn't cost us anything to run CI jobs for open source projects in GitHub.

It does pollute our caches though and don't we still have limits in how much we can run at what speed? Some throttling?

**Comment by ddn0** [comment]
> It does pollute our caches though and don't we still have limits in how much we can run at what speed? Some throttling?

The caches are scoped to the branch, then key, so the only person bothered by running too many jobs is just that PR. https://github.com/actions/cache#cache-scopes

It is fine to add cancellation in this repo as well, but my guess is that it won't affect end-to-end CI latency that much (but I may be wrong).

**Comment by arthurp** [comment]
> The caches are scoped to the branch, then key, so the only person bothered by running too many jobs is just that PR. https://github.com/actions/cache#cache-scopes

Oh I didn't understand that. Thanks.

> It is fine to add cancellation in this repo as well, but my guess is that it won't affect end-to-end CI latency that much (but I may be wrong).

Either I merge this, or I just stop trying to limit my open CI jobs (and just don't cancel them). This was really a personal itch issue.

If you don't see any downside, I would like to merge this.

**Review by ddn0 — APPROVED** [review]

**Pull request merged**
