### PR TITLE
[KAT-2106] Use CUDA 11.5.0

### PR DESCRIPTION
**Pull request by srogatch**

### CODE REVIEW

**Review by arthurp — COMMENTED** [review]
[Conda has 11.5](https://anaconda.org/conda-forge/cudatoolkit) but I don't know if we restrict the version anywhere. Can you check the conda dependencies for cuda? grepping all the `.yaml`/`.yml` files for `"cuda"` should find any references.

**Review by arthurp — APPROVED** [review]
Once the conda thing is resolved, LGTM.

**Comment by srogatch** [comment]
> [Conda has 11.5](https://anaconda.org/conda-forge/cudatoolkit) but I don't know if we restrict the version anywhere. Can you check the conda dependencies for cuda? grepping all the `.yaml`/`.yml` files for `"cuda"` should find any references.

I believe we are installing the latest version of `cudatoolkit-dev`, which is 11.4 ATM https://anaconda.org/conda-forge/cudatoolkit-dev . It's in `external/katana/conda_recipe/environment.yml`.

**Comment by srogatch** [comment]
We do not restrict the version yet - the latest is fine, unless we find some incompatibilities. The worst incompatible thing we currently have is UB in static init/deinit, which should be resolved in https://github.com/KatanaGraph/katana-enterprise/pull/2285

**Pull request merged**
