### PR TITLE
support: move this comment to the header

### PR DESCRIPTION
**Pull request by tylershunt**
Signed-off-by: Tyler Hunt <thunt@katanagraph.com>

### CODE REVIEW

**Comment by tylershunt** [comment]
> lgtm. Is there a difference in the generated documentation between putting this in the header and putting it in the source file?

I don't think so, this is more me trying to figure out what the function does an getting annoyed at having to open the cpp file 😁

**Comment by tylershunt** [comment]
Mac build is failing looks like at the caching service. @ddn0  and @arthurp since they seem to have a handle on the implications there. For now I'm going to blow by it since the build itself seems to pass.
```
Post job cleanup.
/usr/bin/tar --use-compress-program zstd -T0 -cf cache.tzst -P -C /Users/runner/work/katana/katana --files-from manifest.txt
[warning]uploadChunk (start: 100663296, end: 134217727) failed: Cache service responded with 503
/Users/runner/work/_actions/actions/cache/v2/dist/save/index.js:3093
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (/Users/runner/work/_actions/actions/cache/v2/dist/save/index.js:3093:31)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```

**Comment by arthurp** [comment]
> Mac CI is failing looks like at the caching service. @ddn0 and @arthurp since they seem to have a handle on the implications there. For now I'm going to blow by it since the build itself seems to pass.

This one is beyond me. I don't know. @ddn0?

**Comment by ddn0** [comment]
I was just assuming this is a transient failure. If it continues to happen, I can take a look.

**Pull request merged**
